#!/usr/bin/env bash
[[ -n $DEBUG ]] && set -x

set -eou pipefail
IFS=$'\n\t'

get_pods() {
  if [[ "$#" -eq 1 ]]; then
     $KUBECTL get pods | grep $1
  else
    $KUBECTL get pods
  fi
}

main() {
  if [[ -z "${KUBECTL:-}" ]]; then
    if hash kubectl 2>/dev/null; then
      KUBECTL=kubectl
    elif hash kubectl.exe  2>/dev/null; then
      KUBECTL=kubectl.exe
    else
      echo >&2 "kubectl is not installed"
      exit 1
    fi
  fi
	get_pods $@
}
main "$@"

